# Generated by Django 3.1.7 on 2021-04-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0003_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=600)),
                ('user', models.CharField(max_length=30)),
                ('project', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='requests',
            field=models.ManyToManyField(related_name='_user_requests_+', to='collab.Request'),
        ),
    ]
