# Generated by Django 3.1.7 on 2021-06-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0006_auto_20210529_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='visible',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
