# Generated by Django 3.1.7 on 2021-06-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0008_tags_tagname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='tagName',
            field=models.CharField(default='', max_length=200),
        ),
    ]
