# Generated by Django 3.1.7 on 2021-06-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0010_project_allowrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='seenNotifications',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
