# Generated by Django 3.1.7 on 2021-06-08 17:28

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0011_user_seennotifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access',
            field=models.CharField(default="all", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='allowRequest',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
