# Generated by Django 3.1.7 on 2021-06-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0012_auto_20210608_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='access',
            field=models.CharField(max_length=100),
        ),
    ]
