# Generated by Django 3.1.7 on 2021-06-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0013_auto_20210608_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='allowRequest',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='allowRequest',
            field=models.BooleanField(default=True),
        ),
    ]
