# Generated by Django 3.1.7 on 2021-06-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0014_auto_20210609_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=700)),
                ('user', models.CharField(max_length=100)),
            ],
        ),
    ]
