# Generated by Django 3.1.7 on 2021-06-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0016_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='githubId',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
