# Generated by Django 3.1.7 on 2021-06-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0017_auto_20210621_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='message',
            field=models.CharField(default='', max_length=600),
            preserve_default=False,
        ),
    ]
