# Generated by Django 3.1.7 on 2021-07-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0018_request_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='')),
                ('url', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000)),
                ('sender', models.CharField(max_length=30)),
                ('receiver', models.CharField(max_length=30)),
            ],
        ),
    ]
