# Generated by Django 3.1.7 on 2021-07-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0019_imagefield_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefield',
            name='image',
            field=models.ImageField(upload_to='user_images'),
        ),
    ]
