# Generated by Django 3.1.7 on 2021-07-29 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0021_notification_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='seenNotifications',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
