# Generated by Django 3.1.7 on 2021-07-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0022_auto_20210729_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='receiver',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
