# Generated by Django 3.1.7 on 2021-07-31 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0023_request_receiver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interests', models.CharField(max_length=300)),
            ],
        ),
    ]
