# Generated by Django 3.1.7 on 2021-08-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0024_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interests',
            field=models.ManyToManyField(to='collab.Interest'),
        ),
    ]
