# Generated by Django 3.1.7 on 2021-08-20 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0025_user_interests'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 1, 12, 10, 6)),
        ),
    ]
