# Generated by Django 3.1.7 on 2021-08-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0026_auto_20210820_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='admin',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
